# Generated by Django 4.2.5 on 2025-07-24 06:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('greeting_message', models.TextField(blank=True, default=None, null=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('status', models.BooleanField(default=False)),
                ('greeting_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=250, null=True), blank=True, default=list, null=True, size=None)),
                ('suggestive_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=250, null=True), blank=True, default=list, null=True, size=None)),
                ('question', models.TextField(blank=True, default=None, null=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='company_logo/')),
                ('company_description', models.TextField(blank=True, default=None, null=True)),
                ('call_to_action_link', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('call_to_action_prompt', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('timezone', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('conversation_start_flow', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('conversation_end_flow', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('bot_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('container_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('color', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('sitemap_url', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('traning_links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=250, null=True), blank=True, default=list, null=True, size=None)),
                ('traning_status', models.CharField(blank=True, choices=[('UNTRAINED', 'UNTRAINED'), ('TRAINING', 'TRAINING'), ('TRAINED', 'TRAINED')], default='UNTRAINED', max_length=10, null=True)),
                ('theme', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('website_text', models.TextField(blank=True, default=None, null=True)),
                ('ideal_customer_profile', models.TextField(blank=True, default=None, null=True)),
                ('agent_role', models.CharField(blank=True, choices=[('SALES', 'SALES'), ('MARKETING', 'MARKETING'), ('CUSTOMER_SERVICE', 'CUSTOMER_SERVICE'), ('CUSTOMER_SERVICE_ASSISTANT', 'CUSTOMER_SERVICE_ASSISTANT'), ('PROFESSIONAL_ASSISTANT', 'PROFESSIONAL_ASSISTANT'), ('SALES_ASSISTANT', 'SALES_ASSISTANT'), ('MARKETING_ASSISTANT', 'MARKETING_ASSISTANT'), ('SHOWROOM_ASSISTANT', 'SHOWROOM_ASSISTANT')], default=None, max_length=250, null=True)),
                ('landing_page_headline', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('landing_page_subheadline', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('cta_button_label', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('custom_prompt', models.TextField(blank=True, default=None, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('traning_links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=250, null=True), blank=True, default=list, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chatbot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('is_scrape', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.sitemap')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default=None, null=True)),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('company', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='review_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chatbot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('size', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chatbot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='AvatarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chatbot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbot')),
            ],
        ),
    ]
