import { GreetingButtonHelp } from '@/assets/images';

const tokenConstants = {
  ACCESS_TOKEN: 'access_token',
  REFRESH_TOKEN: 'refresh_token',
  USER_DETAIL: 'user_detail',
};

const CALENDLY_LINK = 'https://calendly.com/ujjwalroy/30min';

const TIME_ZONES = [
  { id: 1, value: 'UTC+14:00', name: 'Line Islands Time (LINT)' },
  { id: 2, value: 'UTC+13:00', name: 'Samoa Standard Time (SST)' },
  { id: 3, value: 'UTC+13:00', name: 'Tonga Time (TOT)' },
  { id: 4, value: 'UTC+12:00', name: 'New Zealand Standard Time (NZST)' },
  { id: 5, value: 'UTC+12:00', name: 'Fiji Time (FJT)' },
  { id: 6, value: 'UTC+12:00', name: 'Kamchatka Time (PETT)' },
  { id: 7, value: 'UTC+11:00', name: 'Australian Eastern Daylight Time (AEDT)' },
  { id: 8, value: 'UTC+11:00', name: 'Solomon Islands Time (SBT)' },
  { id: 9, value: 'UTC+11:00', name: 'Vanuatu Time (VUT)' },
  { id: 10, value: 'UTC+10:00', name: 'Australian Eastern Standard Time (AEST)' },
  { id: 11, value: 'UTC+10:00', name: 'Papua New Guinea Time (PGT)' },
  { id: 12, value: 'UTC+10:00', name: 'Chamorro Standard Time (ChST)' },
  { id: 13, value: 'UTC+09:30', name: 'Australian Central Standard Time (ACST)' },
  { id: 14, value: 'UTC+09:00', name: 'Japan Standard Time (JST)' },
  { id: 15, value: 'UTC+09:00', name: 'Korea Standard Time (KST)' },
  { id: 16, value: 'UTC+09:00', name: 'Yakutsk Time (YAKT)' },
  { id: 17, value: 'UTC+08:00', name: 'China Standard Time (CST)' },
  { id: 18, value: 'UTC+08:00', name: 'Singapore Time (SGT)' },
  { id: 19, value: 'UTC+08:00', name: 'Australian Western Standard Time (AWST)' },
  { id: 20, value: 'UTC+08:00', name: 'Irkutsk Time (IRKT)' },
  { id: 21, value: 'UTC+07:00', name: 'Indochina Time (ICT)' },
  { id: 22, value: 'UTC+07:00', name: 'Western Indonesia Time (WIB)' },
  { id: 23, value: 'UTC+06:30', name: 'Cocos Islands Time (CCT)' },
  { id: 24, value: 'UTC+06:00', name: 'Bangladesh Standard Time (BST)' },
  { id: 25, value: 'UTC+06:00', name: 'Omsk Time (OMSK)' },
  { id: 26, value: 'UTC+05:30', name: 'Indian Standard Time (IST)' },
  { id: 27, value: 'UTC+05:30', name: 'Sri Lanka Time (SLT)' },
  { id: 28, value: 'UTC+05:00', name: 'Pakistan Standard Time (PKT)' },
  { id: 29, value: 'UTC+05:00', name: 'Yekaterinburg Time (YEKT)' },
  { id: 30, value: 'UTC+04:30', name: 'Afghanistan Time (AFT)' },
  { id: 31, value: 'UTC+04:00', name: 'Gulf Standard Time (GST)' },
  { id: 32, value: 'UTC+04:00', name: 'Moscow Standard Time (MSK)' },
  { id: 33, value: 'UTC+04:00', name: 'Azerbaijan Standard Time (AZT)' },
  { id: 34, value: 'UTC+03:30', name: 'Iran Standard Time (IRST)' },
  { id: 35, value: 'UTC+03:00', name: 'Eastern European Time (EET)' },
  { id: 36, value: 'UTC+03:00', name: 'Arabia Standard Time (AST)' },
  { id: 37, value: 'UTC+02:00', name: 'Central European Time (CET)' },
  { id: 38, value: 'UTC+02:00', name: 'South Africa Standard Time (SAST)' },
  { id: 39, value: 'UTC+02:00', name: 'Israel Standard Time (IST)' },
  { id: 40, value: 'UTC+01:00', name: 'Western European Time (WET)' },
  { id: 41, value: 'UTC+01:00', name: 'Central Africa Time (CAT)' },
  { id: 42, value: 'UTC', name: 'Coordinated Universal Time (UTC)' },
  { id: 43, value: 'UTC-01:00', name: 'Azores Time (AZOT)' },
  { id: 44, value: 'UTC-02:00', name: 'Brasília Time (BRT)' },
  { id: 45, value: 'UTC-03:00', name: 'Argentina Time (ART)' },
  { id: 46, value: 'UTC-03:00', name: 'Atlantic Standard Time (AST)' },
  { id: 47, value: 'UTC-04:00', name: 'Eastern Standard Time (EST)' },
  { id: 48, value: 'UTC-04:00', name: 'Chile Standard Time (CLT)' },
  { id: 49, value: 'UTC-04:30', name: 'Venezuela Time (VET)' },
  { id: 50, value: 'UTC-05:00', name: 'Central Standard Time (CST)' },
  { id: 51, value: 'UTC-05:00', name: 'Eastern Standard Time (EST)' },
  { id: 52, value: 'UTC-06:00', name: 'Mountain Standard Time (MST)' },
  { id: 53, value: 'UTC-06:00', name: 'Central America Time (CST)' },
  { id: 54, value: 'UTC-07:00', name: 'Pacific Standard Time (PST)' },
  { id: 55, value: 'UTC-08:00', name: 'Alaska Standard Time (AKST)' },
];
const LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Russian',
  'Japanese',
  'Chinese',
  'Korean',
  'Arabic',
  'Hindi',
  'Bengali',
];

const CONVERSATION_START = ['Gathering Information'];

const CONVERSATION_END = ['Sign up for demo/calendly meeting', 'Subscribe products'];
const COUNTRYLIST = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Åland Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'AndorrA', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Cote D'Ivoire", code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: "Korea, Democratic People'S Republic of", code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao People'S Democratic Republic", code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia, Federated States of', code: 'FM' },
  { name: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russian Federation', code: 'RU' },
  { name: 'RWANDA', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia and Montenegro', code: 'CS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];

const FORM_HELPER = {
  chatbot_name: {
    title: 'Tips for you',
    body: 'Enter a unique name for your agent to personalize the conversation. This name will be visible to your clients.',
  },
  greeting_message: {
    title: 'Tips for you',
    body: 'Greeting message is the first greetings that your clients are greeted with when they open up your website.',
    image: GreetingButtonHelp,
  },
  greeting_button: {
    title: 'Tips for you',
    body: 'Greeting buttons are the quick reply button to interact with the bot. They are only visible at the starting of the conversation.',
    image: GreetingButtonHelp,
  },
  chatbot_avatar: {
    title: 'Tips for you',
    body: 'Chatbot avatar is the avatar icon seen on the right bottom corner of the website in which agent is embedded.',
    image: GreetingButtonHelp,
  },
  company_name: {
    title: 'Tips for you',
    body: 'Provide your company name to personalize your interactions.',
  },
  status: {
    title: 'Tips for you',
    body: "Select your status as either 'Online' or 'Offline' to control availability of the bot.",
  },
  call_to_action: {
    title: 'Tips for you',
    body: 'Choose how would you like to end your conversation.',
  },
};

const COMPANY_SECTORS = [
  'Technology',
  'Finance',
  'Healthcare',
  'Manufacturing',
  'Retail',
  'Telecommunications',
  'Energy',
  'Hospitality',
  'Transportation',
  'Entertainment',
  'Education',
  'Real Estate',
  'Automotive',
  'Agriculture',
  'Media',
  'Others',
];

const COMPANY_SIZES_EU = [
  'Microenterprise (1-9 employees)',
  'Small Enterprise (10-49 employees)',
  'Medium-sized Enterprise (50-249 employees)',
  'Large Enterprise (250+ employees)',
];

export {
  CALENDLY_LINK,
  COMPANY_SECTORS,
  COMPANY_SIZES_EU,
  CONVERSATION_END,
  CONVERSATION_START,
  COUNTRYLIST,
  FORM_HELPER,
  LANGUAGES,
  TIME_ZONES,
  tokenConstants,
};
