const env = import.meta.env;

export const CONFIG = {
  BASE_API_URL: env.VITE_BACKEND_URL,
  BOT_DOMAIN: env.VITE_BOT_DOMAIN,
  ENABLE_AUTO_REPLY: env.ENABLE_AUTO_REPLY || true,

  STRIPE_PUBLIC_KEY: env.VITE_STRIPE_PUBLIC_KEY,
  NEWSLETTER_WEB: env.VITE_NEWSLETTER_WEB,
  ENCRYPTION_KEY: env.VITE_ENCRYPTION_KEY,
  NEWSLETTER_URL: env.VITE_NEWSLETTER_URL,
  DEMO_USERID: env.VITE_DEMO_ACCOUNT_USERID,
  DEMO_PASSWORD: env.VITE_DEMO_ACCOUNT_PASSWORD,
  MIXPANEL_TOKEN: env.VITE_MIXPANEL_TOKEN,
};
