export const endpoints = {
  auth: {
    signIn: '/account/login/',
    signUp: '/account/signup/',
    subscribe: '/subscribe/subscribe/',
    subscribeYearly: 'subscribe/upgrade-yearly/',
    changeSubscription: '/subscribe/change-current-subscription/',
    resetPassword: '/account/reset-password/',
    me: '/account/me/',
    changePassword: '/account/change-password/',
    verify: '/account/verify/',
    resendEmail: '/account/verify-email/',
  },
  review: {
    add: '/review/',
    list: '/review/get_review_by_chatbot_id/',
    reviewDetail: '/review/:id/',
    updateReview: '/review/:id/',
  },
  blogs: {
    allBlogs: 'news/?search=Unreal&ordering=-created_at',
    blogDetail: 'news/:id',
  },
  chatbot: '/chatbot/',
  chatbotInfo: '/chatbot/count_chatbot/',
  file: '/file/',
  fileDetail: '/file/:id/',
  deployChatbot: '/chatbot/:id/deploy_chat_bot/',
  chatBotDetail: '/chatbot/:id/',
  allSessionById: '/chatbot/:id/get_all_session_by_chat_id/',
  getSessionInfo: '/chatbot/:id/get_session_info_by_id/',
  getLeadList: 'chatbot/:id/get_all_lead/',
  analyzeConversation: '/chatbot/:id/analyze_conversation/',
  updateChatBot: '/chatbot/:id/update_chat_bot/',
  deleteChatBot: '/chatbot/:id/delete_chat_bot/',
  stripe: {
    cardDetails: '/subscribe/card-details/',
    paymentHistory: '/subscribe/payment-history/',
    changeCard: '/subscribe/change-card/',
    deactiveSubscription: '/subscribe/pause/',
    activeSubscription: '/subscribe/resume/',
    deleteAccount: '/subscribe/delete/',
  },
  billingAddress: {
    get: '/billing-address/',
    patch: '/billing-address/:id/',
  },
  total_projects: '/chatbot/progression_status_all/',
  total_active_bots: '/chatbot/progression_status_active/',
  total_sessions: '/chatbot/session_progression_status/',
  avg_time_to_conversion: '/chatbot/session_progression_conversion/',
  scrapeSiteMap: '/scrape-sitemap_links',
  siteMap: '/sitemap/',
  siteMapById: '/sitemap/get_sitemap_by_chatbot_id/',
  progressionbyBotId: '/chatbot/:id/get_progression_data/',
  peakHours: '/chatbot/:id/get_peak_hours/',
  queryCount: '/chatbot/get_query_count/',
  analyzeSession: '/chatbot/:id/analyze_session/',
  getAllSession: '/chatbot/get_all_session/',
};
