# Generated by Django 4.2.5 on 2023-10-17 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0002_alter_subscription_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
