version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:stable

jobs:
  deploy:
    executor: default
    parameters:
      env-file:
        type: string
        default: env/.env.docker
      host:
        type: string
        default: $DEV_HOST
    steps:
      - checkout
      - run:
          name: deploy code to ec2 instance
          command: |
            ssh -o StrictHostKeyChecking=no << parameters.host >> 'exit'
            ssh << parameters.host >> 'rm -rf ~/seethoschatbotai-bot-manager/ || true'
            scp -r /home/circleci/project/ << parameters.host >>:~/seethoschatbotai-bot-manager/
            ssh << parameters.host >> 'cd ~/seethoschatbotai-bot-manager && docker build -f Dockerfile -t seethoschatbotai-bot-manager:latest .'
            ssh << parameters.host >> 'cd ~/seethoschatbotai-bot-manager && docker container rm -f seethoschatbotai-bot-manager || true'
            ssh << parameters.host >> 'cd ~/seethoschatbotai-bot-manager && docker image prune -f'
            ssh << parameters.host >> 'cd ~/seethoschatbotai-bot-manager && docker run -d --network frontend --env-file << parameters.env-file >> --memory="2g" --cpus="1" --name seethoschatbotai-bot-manager seethoschatbotai-bot-manager:latest'

workflows:
  version: 2

  deploy-manager-alpha:
    jobs:
      - deploy:
          host: $DEV_HOST
          env-file: env/.env.dev.docker
          filters:
            branches:
              only:
                - develop

  deploy-manager-prod:
    jobs:
      - deploy:
          host: $PROD_HOST
          env-file: env/.env.prod.docker
          filters:
            branches:
              only:
                - master
  
  deploy-manager-seethos:
    jobs:
      - deploy:
          host: $SEETHOS
          env-file: env/.env.seethos.docker
          filters:
            branches:
              only:
                - seethos

