export const query = {
  getCampignList: 'CAMPAIGN_MANAGEMENT_GET_CAMPAIGN_LIST',
  getSenderEmailList: 'CAMPAIGN_MANAGEMENT_GET_SENDER_EMAIL_LIST',
  getCampaignById: 'CAMPAIGN_MANAGEMENT_GET_CAMPAIGN_BY_ID',
  getSequenceCampaignList: 'CAMPAIGN_MANAGEMENT_GET_SEQUENCE_CAMPAIGN_LIST',
};
